import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import API from "../../services/api";

export default function AdminDashboard() {
	const [dashboard, setDashboard] = useState(null);
	useEffect(() => { API.get("/admin/dashboard").then(({ data }) => setDashboard(data)).catch(() => setDashboard({ stats: {}, recentBookings: [] })); }, []);
	const stats = [[dashboard?.stats?.bookings || 0, "Total bookings", "All time"], [dashboard?.stats?.users || 0, "Customers", "Registered users"], [dashboard?.stats?.reviews || 0, "Reviews", "Customer feedback"]];
	return <div><div className="admin-heading"><div><div className="eyebrow">OPERATIONS CONSOLE</div><h1>Studio overview</h1><p>Monitor the business, appointments, and customer activity.</p></div><Link className="button" to="/admin/services">Post a service</Link></div><div className="stats-grid">{stats.map(([value, label, meta]) => <article className="stat" key={label}><span>{label}</span><strong>{value}</strong><small>{meta}</small></article>)}</div><section className="admin-panel"><div className="panel-heading"><h2>Recent activity</h2><Link to="/admin/bookings">View all ↗</Link></div>{dashboard?.recentBookings?.length ? dashboard.recentBookings.slice(0, 5).map((booking) => <div className="booking-row" key={booking._id}><div className="booking-time">{new Date(booking.pickupDate).toLocaleDateString(undefined, { month: "short", day: "numeric" })}</div><div><strong>{booking.service?.name || "Service booking"}</strong><span>{booking.user?.name || "Customer"} · {booking.sareeCount} saree(s)</span></div><b className={`status ${booking.status === "Pending" ? "status--pending" : "status--confirmed"}`}>{booking.status}</b></div>) : <p className="muted">No bookings have been created yet.</p>}</section><section className="admin-panel review-dashboard-panel"><div className="panel-heading"><h2>Latest reviews</h2><Link to="/admin/reviews">Manage all ↗</Link></div>{dashboard?.recentReviews?.length ? dashboard.recentReviews.map((review) => <div className="admin-review" key={review._id}><div><strong>{review.userName}</strong><span>{review.service?.name || "Service"} · {new Date(review.createdAt).toLocaleDateString()}</span></div><strong className="review-rating">{"★".repeat(review.rating)}</strong></div>) : <p className="muted">No reviews have been submitted yet.</p>}</section></div>;
}
